name: .NET Core Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: ./IrcWidget.Web

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./IrcWidget.Web

      - name: Test
        run: dotnet test --configuration Release --no-restore --verbosity normal
        working-directory: ./IrcWidget.Web
